export const CHARACTER_CHAT_DEFAULT_FEMALE_ID =
  process.env.CHARACTER_CHAT_DEFAULT_FEMALE_ID || "";
export const CHARACTER_CHAT_DEFAULT_FEMALE_NAME =
  process.env.CHARACTER_CHAT_DEFAULT_FEMALE_NAME || "";

export const CHARACTER_CHAT_DEFAULT_MALE_ID =
  process.env.CHARACTER_CHAT_DEFAULT_MALE_ID || "";
export const CHARACTER_CHAT_DEFAULT_MALE_NAME =
  process.env.CHARACTER_CHAT_DEFAULT_MALE_NAME || "";
